
GET http://localhost:3000/api/permission/all

###

GET http://localhost:3000/api/user/all

###

GET https://www.cambria-leadsystem-server.com/api/user/all

###

GET http://localhost:3000/api/user/all

###

GET http://localhost:3000/api/city/all

###
GET http://localhost:3000/api/leadheader/getall

###
GET http://localhost:3000/drivers/ByDriverId/1
  v  
###
POST http://localhost:3000/drivers/CreateDriver
Content-Type: application/json

{
    "Id" : "01",
    "Email" : "climaco.onde10@gmail.com",
    "Password" : "onde1994",
    "Salt" : "SALT",
    "FirstName" : "Climaco",
    "LastName" : "Onde",
    "Address" : "Minglanilla",
    "Phone" : "Jr",
    "Verified" : "true",
    "Otp" : "456525",
    "Lat" : "456525",
    "Lng" : "456525",
    "IsAvailable" : "true"
}

###

POST http://localhost:3000/api/user/CreateUser
Content-Type: application/json

{
   
    "UserName" : "climaco1994",
    "Password" : "onde1994",
    "Email" : "climaco.onde10@gmail.com",
    "FirstName" : "huebe",
    "LastName" : "Onde",
    "MiddleName" : "",
    "UserType" : "ADMIN",
    "Suffix" : "Jr",
    "BirthDate" : "07/10/1994",
    "Mobile" : "0950346030",
    "Status" : "Accept: ",
    "Ludatetime" : "07/10/1994"
}

###

POST http://localhost:3000/api/source/CreateSource
Content-Type: application/json

{
    "SourceId" : "1",
    "Code" : "INT",
    "Name" : "INTERNET",
    "Description" : "Source from Internet",
    "Enabled" : "true",
    "Default" : "true"
}
 
 

###

DELETE http://localhost:3000/api/permission/DeletePermission/659d21a98285e854c2bbffe2


###

