
GET http://localhost:3000/api/notes/all

###

GET http://localhost:3000/api/user/all

###

GET http://localhost:3000/api/city/all

###
GET http://localhost:3000/api/leadheader/getall

###
GET http://localhost:3000/drivers/ByDriverId/1
  v  
###
POST http://localhost:3000/drivers/CreateDriver
Content-Type: application/json

{
    "Id" : "01",
    "Email" : "climaco.onde10@gmail.com",
    "Password" : "onde1994",
    "Salt" : "SALT",
    "FirstName" : "Climaco",
    "LastName" : "Onde",
    "Address" : "Minglanilla",
    "Phone" : "Jr",
    "Verified" : "true",
    "Otp" : "456525",
    "Lat" : "456525",
    "Lng" : "456525",
    "IsAvailable" : "true"
}

###

POST http://localhost:3000/api/source/CreateUser
Content-Type: application/json

{
    "UserCode" : "CSO",
    "UserName" : "root@cornestech.co",
    "Password" : "P@ssw0rd",
    "Email" : "root@cornestech.co",
    "FullName" : "Climaco Onde Jr",
    "FirstName" : "Climaco",
    "LastName" : "Onde",
    "MiddleName" : "",
    "UserType" : "ADMIN",
    "Suffix" : "Jr",
    "BirthDate" : "07/10/1994",
    "Mobile" : "0950346030",
    "Status" : "Accept: ",
    "Ludatetime" : "07/10/1994"
}

###

POST http://localhost:3000/api/source/CreateSource
Content-Type: application/json

{
    "SourceId" : "1",
    "Code" : "INT",
    "Name" : "INTERNET",
    "Description" : "Source from Internet",
    "Enabled" : "true",
    "Default" : "true"
}
 
 

###

DELETE http://localhost:3000/drivers/DeleteDriver/1


###

